CREATE WAREHOUSE IF NOT EXISTS NYC_MOBILITY_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

DATABASE IF NOT EXISTS NYC_MOBILITY;

USE DATABASE NYC_MOBILITY;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;


SHOW SCHEMAS;

GRANT USAGE ON SCHEMA STAGING TO ROLE SYSADMIN;

GRANT CREATE TABLE ON SCHEMA STAGING TO ROLE SYSADMIN;NYC_MOBILITY;

GRANT CREATE VIEW ON SCHEMA STAGING TO ROLE SYSADMIN;