USE DATABASE NYC_MOBILITY;

CREATE OR REPLACE STORAGE INTEGRATION NYC_MOBILITY_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '<YOUR_AWS_IAM_ROLE_ARN>'
STORAGE_ALLOWED_LOCATIONS = (
    's3://nyc-mobility-data-platform/raw/'
);