USE DATABASE NYC_MOBILITY;

CREATE OR REPLACE STAGE NYC_MOBILITY.RAW.YELLOW_TAXI_STAGE
URL = 's3://nyc-mobility-data-platform/raw/yellow_taxi/'
STORAGE_INTEGRATION = NYC_MOBILITY_S3_INTEGRATION;

CREATE OR REPLACE FILE FORMAT NYC_MOBILITY.RAW.PARQUET_FORMAT
TYPE = PARQUET
USE_LOGICAL_TYPE = TRUE
USE_VECTORIZED_SCANNER = TRUE;

CREATE OR REPLACE STAGE NYC_MOBILITY.RAW.GREEN_TAXI_STAGE
URL = 's3://nyc-mobility-data-platform/raw/green_taxi/'
STORAGE_INTEGRATION = NYC_MOBILITY_S3_INTEGRATION;