USE DATABASE NYC_MOBILITY;

TRUNCATE TABLE NYC_MOBILITY.RAW.YELLOW_TAXI_RAW;

COPY INTO NYC_MOBILITY.RAW.YELLOW_TAXI_RAW
FROM @NYC_MOBILITY.RAW.YELLOW_TAXI_STAGE
FILE_FORMAT = NYC_MOBILITY.RAW.PARQUET_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- Green Taxi RAW Load

USE DATABASE NYC_MOBILITY;

TRUNCATE TABLE NYC_MOBILITY.RAW.GREEN_TAXI_RAW;

COPY INTO NYC_MOBILITY.RAW.GREEN_TAXI_RAW
FROM @NYC_MOBILITY.RAW.GREEN_TAXI_STAGE
FILE_FORMAT = NYC_MOBILITY.RAW.PARQUET_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';