USE DATABASE NYC_MOBILITY;

CREATE OR REPLACE STAGE NYC_MOBILITY.RAW.WEATHER_STAGE
URL = 's3://nyc-mobility-data-platform/raw/weather/'
STORAGE_INTEGRATION = NYC_MOBILITY_S3_INTEGRATION;

LIST @NYC_MOBILITY.RAW.WEATHER_STAGE;