USE DATABASE NYC_MOBILITY;

CREATE OR REPLACE TABLE NYC_MOBILITY.RAW.WEATHER_RAW (
    STATION_ID VARCHAR,
    DATE DATE,
    MAX_TEMPERATURE_C FLOAT,
    MIN_TEMPERATURE_C FLOAT,
    PRECIPITATION_MM FLOAT,
    SNOWFALL_MM FLOAT
);