USE DATABASE NYC_MOBILITY;

COPY INTO NYC_MOBILITY.RAW.WEATHER_RAW
FROM @NYC_MOBILITY.RAW.WEATHER_STAGE
FILE_FORMAT = NYC_MOBILITY.RAW.PARQUET_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';